import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FacilityAuthProvider } from './context/AuthContext/context';
import { QueryClient } from '@tanstack/react-query';
import { TanstackProvider } from './utils/TanstackProvider';

const inter = Inter({ subsets: ['latin'] });

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
